import Head from 'next/head';
import styles from '@/styles/authentication/authentication.module.css';
import Login from '@/components/authentication/Login';
import { useState } from 'react';
import Register from '@/components/authentication/Register';
import Image from 'next/image';

export default function Home() {
  const [isRegistered, setIsRegistered] = useState(true);

  const toggleForm = () => setIsRegistered(!isRegistered);

  return (
    <>
      <Head>
        <title>Dashboard - Autenticazione</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <section className={`${styles.form} flex_column`} style={{ gap: '20px' }}>
          <Image
            src='/logo.png'
            height={90}
            width={90}
            alt='logo'
            style={{ objectFit: 'cover', alignSelf: 'center' }}
          />
          {isRegistered ? <Login toggleForm={toggleForm} /> : <Register toggleForm={toggleForm} />}
        </section>
      </main>
    </>
  );
}
