import Head from 'next/head';
import styles from '@/styles/dashboard/Dashboard.module.css';
import Navbar from '@/components/dashboard/Navbar';
import { PropsWithChildren } from 'react';

const DashboardLayout = ({ children }: PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>Dashboard - Home</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.grid}>
        <Navbar />
        <section className={styles.content}>{children}</section>
      </main>
    </>
  );
};

export default DashboardLayout;
